# Generated by Django 5.0.4 on 2024-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoController', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
